name: Tests

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: E2E tests
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/yarn

      - uses: ./.github/workflows/build

      - name: Run tests
        run: yarn test:ci

      - name: Comment in failing tests
        uses: mattallty/jest-github-action@v1.0.3
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo unit tests already executed'
          coverage-comment: false
